# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mehrad Rousta
subtitle: Geek, Human, And some other things
description: I'm Mehrad Rousta, from Tehran, Developer and some other stuff.
keywords:
author: Mehrad Rousta
language: en
timezone: Asia/Tehran

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mehrad.js.org/en
root: /en/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: ../publics/en
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Theme: https://github.com/probberechts/hexo-theme-cactus
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: shell
  command: cd .. && npm run-script deploy

githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  styles:
    display: inline
    vertical-align: bottom
  localEmojis:

image_caption:
  enable: true 
  class_name: image-caption #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'

# hexo-generator-amp
# Advanced Settings of hexo-amp-generator
generator_amp:
  # 2. Template Option
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   https://www.gravatar.com/avatar/85e63edadccdfe37ec7759cadfefc6a6?s=192
    width:  600 # width <= 600px
    height: 60  # width <= 60px
  logo_topImage:                                  #(optional)
    path:   https://www.gravatar.com/avatar/85e63edadccdfe37ec7759cadfefc6a6?s=192       #(optional)
    width:  1024                                  #(optional)
    height: 400                                   #(optional)
  substituteTitleImage: 
    path:   https://www.gravatar.com/avatar/85e63edadccdfe37ec7759cadfefc6a6?s=192
    width:  1024 # width >= 696px
    height: 800
  placeholderImg:                                 #(optional)
    path: https://www.gravatar.com/avatar/85e63edadccdfe37ec7759cadfefc6a6?s=192
  cssFilePath:      sample/sample-amp.css         #(optional) Location of css or stylus or sass file to use
  templateFilePath: sample/sample-amp.ejs         #(optional) Location of ejs or pug template file to use
  generateAmpPath: :year/:month/:day/:title/amp/  #(optional) Custom AMP HTML Path
  # Sample Template's option
  theme:                                        #(optional) Sample AMP template's option
     menu:                                      #(optional) Sample AMP template's menu option
       diary: /categories/diary/                #(optional) example menu
       archives: /archives                      #(optional) example menu
    #  facebook_app_id: 1234567890                #(optional) api_id is necessary with the facebook's social button.
    #  facebook_admins: 1234567890                #(optional) admins is necessary with the facebook's social button.
     share_button:                              #(optional) Share button option
       twitter: true                            #(optional) Enable Twitter share button
       facebook: false                           #(optional) Enable Facebook share button
       google: true                             #(optional) Enable Goolge+ share button
      #  hatena: true                             #(optional) Enable Hatena share button
      #  tumblr: true                             #(optional) Enable Tumblr share button
     category_posts: true                       #(optional) Enable category posts
     category_posts_detailed: true              #(optional) Enable detailed category posts
     latests: true                              #(optional) Enable latests posts
     list_limts: 6                              #(optional) This option limit the number of display in the above lists (default:5)
     authorLink:                                #(optional) Enable footer profile link
       mail_url: mailto:mehrad77@gmail.com
       twitter_id: mehrad77
      #  facebook_id: xxx
       youtube_channel: https://www.youtube.com/channel/UCvVVYLa5sDjX8W9OknMmxRQ
       instagram_id: mehrad77
       github_id: mehrad77
  # 3. Google Analytics Option
  google_analytics: UA-103618500-1                #(optional)
  # 4. Minify Option
  # html_minifier:                                  #(optional) https://github.com/kangax/html-minifier
  # 5. Display warning Log
  warningLog: true                                #(optional)
  # 6. Cache Option
  cache: hexo-generator-amp-cached.json           #(optional) Enable cache (Improve generation speed)
  # 7. Automatically validate AMP HTML
  validateAMP: true                               #(optional)
# 8. Footer Option (authorDetail)
authorDetail:
  authorReading: Mehrad Rousta            #(optional)
  avatar:                                         #(optional)
    path:  https://www.gravatar.com/avatar/85e63edadccdfe37ec7759cadfefc6a6?s=150              #(optional)
    width:  150                                   #(optional)
    height: 150                                   #(optional)
  description: Developer, Blogger, Enthusiastic and Geek;                  #(optional)
# copyright_notice: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"> <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /> </a>

#Mehrad Strings
mehrad:
  also_see:
  minutes: minutes


# #Podcast  (https://github.com/owen8877/hexo-generator-podcast)
# podcast:
#     type: rss2
#     path: podcast.xml
#     limit: 20
#     hub:
#     url: https://mehrad.js.org/podcast
#     description: 
#     language: fa-IR
#     copyright: "COPYRIGHT"
#     owner: ITUNES-OWNER
#     email: mehrad77@gmail.com
#     category: podcast
